# Generated by Django 3.0.2 on 2021-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210218_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_of_user',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=10),
        ),
    ]
